//
// Created by Matthew Eshleman on 4/9/21.
//

#ifndef CMSEXECUTIONOPTION_H
#define CMSEXECUTIONOPTION_H


typedef enum ExecutionOption
{
    EXECUTION_OPTION_NORMAL,
    EXECUTION_OPTION_UNIT_TEST
} ExecutionOptionT;

#endif //ACTIVEOBJECTUNITTESTINGDEMO_CMSEXECUTIONOPTION_H
